AWSTemplateFormatVersion: '2010-09-09'
Description: "NovaMuse frontend: S3 + CloudFront + Route53 for https://novamusequotes.c3devs.com"

Parameters:
  DomainName:
    Type: String
    Default: novamusequotes.c3devs.com

  HostedZoneName:
    Type: String
    Default: c3devs.com.

  CertificateArn:
    Type: String
    Description: Wildcard ACM cert for *.c3devs.com (must be in us-east-1)
  
  BucketName:
    Type: String
    Default: novamuse-frontend

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: {"Ref": "BucketName"}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FrontendOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: novamuse-frontend-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - {"Ref": "DomainName"}
        ViewerCertificate:
          AcmCertificateArn: {"Ref": "CertificateArn"}
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: S3Origin
            DomainName: {"Fn::GetAtt": ["FrontendBucket", "RegionalDomainName"]}
            OriginAccessControlId: {"Ref": "FrontendOAC"}
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: {"Ref": "FrontendBucket"}
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontOAC
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: {"Fn::Sub": "${FrontendBucket.Arn}/*"}
            Condition:
              StringEquals:
                AWS:SourceArn: {"Fn::Sub": "arn:aws:cloudfront::${AWS::AccountId}:distribution/${FrontendDistribution}"}

  FrontendAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: {"Ref": "HostedZoneName"}
      Name: {"Ref": "DomainName"}
      Type: A
      AliasTarget:
        DNSName: {"Fn::GetAtt": ["FrontendDistribution", "DomainName"]}
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

Outputs:
  CloudFrontDomainName:
    Value: {"Fn::GetAtt": ["FrontendDistribution", "DomainName"]}

  BucketName:
    Value: {"Ref": "FrontendBucket"}
